version: 2

# Set the OS, Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Install your package + documentation dependencies
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

# Build HTML documentation using Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optional: build PDF & EPUB (you can remove if not needed)
formats:
  - htmlzip
  - pdf
  - epub
